### ISSUE TITLE
Create fields only if not exist

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/limburg-flood-impact#2]

**Comment by JanCaha** [comment]
So if the field with given name already exists, skip the calculation of the field and leave the original values?

**Comment by leendertvanwolfswinkel** [comment]
No, overwrite the existing values. The main use case is "Oh, I made a mistake (selected wrong input, etc), let me re-do everything from this step forward"

**Comment by JanCaha** [comment]
That is the way most of the tools should work right now. I will double check. The only difference is the `check_address` tool, where the attribute **heeft_adres** is deleted, because the layes are joined using SQL and having the attribute here would cause issues.

**Comment by leendertvanwolfswinkel** [comment]
Tested again and I can't reproduce the problem I had before. Closing this issue
