### ISSUE TITLE
Add styling to end result

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/limburg-flood-impact#3]
Make separate processing algorithm

**Comment by leendertvanwolfswinkel** [comment]
Waterschap Limburg will share styling file

**Comment by JanCaha** [comment]
Time estimate: 2-4 hours (depends if there are more styling files)

The algorithm will only require selection of layer and attribute and applies correct styling, correct?

**Comment by leendertvanwolfswinkel** [comment]
I think (at least in the v1.0 version, it will be super simple, just `layer.loadNamedStyle()` wrapped in a processing algorithm.

**Comment by leendertvanwolfswinkel** [comment]
I have uploaded 3 styling files to branch `style`

The way I would like the algorithm to work:
- User selects buildings layer
- User selects column to style; options: landelijk_t10, landelijk_t25, landelijk_t100, stedelijk_10, stedelijk_t25, stedelijk_t100, gebiedsbreed_10, gebiedsbreed_t25, gebiedsbreed_t100, klasse_t10, klasse_25, klasse_25.
- If user selects a column that the layer does not have, tell user and end algorithm
- If the columns are available the appropriate styling should be applied: `landelijk_stedelijk.qml` for landelijk_t10, landelijk_t25, landelijk_t100, stedelijk_10, stedelijk_t25, stedelijk_t100; `gebiedsbreed.qml` for gebiedsbreed_10, gebiedsbreed_t25, gebiedsbreed_t100; `klasse.qml` for klasse_t10, klasse_25, klasse_25

**Comment by JanCaha** [comment]
Added the tool to the latest plugin version.
