### ISSUE TITLE
Testing against the flood protection norm

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/limburg-flood-impact#4]
Each building can be tested against the flood protection norm. 

Algorithm parameters:
- Buildings layer
- Normgebieden layer; polygons with attribute `NORM`, with possible values `geen`, `1:10`, `1:25`, or `1:100`. Example: 
[Norm.zip](https://github.com/nens/limburg-flood-impact/files/10557503/Norm.zip)

Algorithm creates the following new fields:
- `in_normgebied_t10` boolean
- `in_normgebied_t25` boolean
- `in_normgebied_t100` boolean
- `normgebied` string. Possible values: `geen`, `1:10`, `1:25`, or `1:100`
- `toetsingsklasse` string. Values are copied from either `klasse_t10`, `klasse_t25` or `klasse_t100`
- `voldoet_aan_norm` string. Possible values: ‘ja’ or ‘nader onderzoeken’

The following method is used for this:
- Determine in which flood protection norm zone the building is located. First, in the boolean fields `in_normgebied_t10`, `in_normgebied_t25` and `in_normgebied_t100`, it is registered whether the building is (partly) located in the relevant standard area.
- Subsequently, the applicable standard is registered in the string field 'normgebied'. If the building is located in more than 1 normgebied (the building is on the border), the highest standard is used (1:100 above 1:25 above 1:10 above “geen”).
- If `normgebied` = "1:100", the value in `klasse_t100` is copied to the “toetsingsklasse” attribute
- If `normgebied` = "1:25",  the value in `klasse_t25` is copied to the “toetsingsklasse” attribute
- If `normgebied` = "1:10",  the value in `klasse_t10` is copied to the “toetsingsklasse” attribute
- If `normgebied` = "geen", “toetsingsklasse” get the value "n.v.t."
- "voldoet_aan_norm" is filled based on the value of "toetsingsklasse". See the translation table https://github.com/nens/limburg-flood-impact/blob/main/misc/classificatie.xlsx).

**Comment by leendertvanwolfswinkel** [comment]
WFS service may be available, @leendertvanwolfswinkel add to documentation

**Comment by JanCaha** [comment]
Are there some relevant test data to use? I remember that I asked for I believe that we never solved that.

**Comment by leendertvanwolfswinkel** [comment]
I added test data and rewrote the ticket to make it more clear. The last part was removed due to discussions with the client this morning

**Comment by JanCaha** [comment]
Time estimate: 4-6 hours

**Comment by JanCaha** [comment]
This tool now exist in both qgis plugin and python package.

**Comment by leendertvanwolfswinkel** [comment]
Hi @JanCaha, I have tested this and get the following error:

QGIS version: 3.22.3-Białowieża
QGIS code revision: 1628765ec7
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.4.1
GEOS version: 3.10.0-CAPI-1.16.0
PROJ version: Rel. 8.2.1, January 1st, 2022
PDAL version: 2.3.0 (git-version: 9f35b7)
Algorithm started at: 2023-02-08T17:17:04
Algorithm 'Test Against Flood Protection Norm' starting…
Input parameters:
{ 'BuildingsLayer' : 'C:/Temp/limburg-flood-impact test data/pand_sibbergrubbe.gpkg|layername=pand_sibbergrubbe', 'FloodLayer' : 'C:\\Temp\\limburg-flood-impact test data\\flood_protection_norm_sibbergrubbe.gpkg|layername=flood_protection_norm_sibbergrubbe' }

Traceback (most recent call last):
File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\limburg_flood_impact_plugin\processing\tool_test_against_flood_protection_norm.py", line 65, in processAlgorithm
test_against_flood_protection_norm(Path(buildings_datasource),
File "C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\limburg_flood_impact_plugin\deps\limburg_flood_impact-0.3.0-py3-none-any.whl\limburg_flood_impact\test_against_flood_protection_norm.py", line 35, in test_against_flood_protection_norm
voldoet_aan_norm_classes = get_voldoet_aan_norm_classes()
File "C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\limburg_flood_impact_plugin\deps\limburg_flood_impact-0.3.0-py3-none-any.whl\limburg_flood_impact\test_against_flood_protection_norm.py", line 13, in get_voldoet_aan_norm_classes
classificate_layer: ogr.Layer = classificate_ds.GetLayer()
AttributeError: 'NoneType' object has no attribute 'GetLayer'

Execution failed after 0.26 seconds

Loading resulting layers
Algorithm 'Test Against Flood Protection Norm' finished

**Comment by leendertvanwolfswinkel** [comment]
Data to reproduce the issue: 

[sibbergrubbe flood protection norm bug.zip](https://github.com/nens/limburg-flood-impact/files/10687655/sibbergrubbe.flood.protection.norm.bug.zip)

**Comment by JanCaha** [comment]
The issue is fixed and the new plugin version is available on Slack channel.

**Comment by leendertvanwolfswinkel** [comment]
- I found another bug, fixed it on branch `bugfix_issue_4`. Please review and include in next release.
- The norm is not always assigned correctly. For example, this building is partly in a '1:25' area, but has toetsingsklasse "n.v.t.":
![image](https://user-images.githubusercontent.com/26224299/220198325-15b7df2b-b2b3-4b3b-9410-be61de496491.png)
![image](https://user-images.githubusercontent.com/26224299/220198500-b7fca05d-df90-4772-af94-fa4c7ab256cb.png)
![image](https://user-images.githubusercontent.com/26224299/220198670-7d0e6bb9-fb4c-439f-8629-16aa6504c074.png)
