### ISSUE TITLE
Add check for 'buildings' layer input for 'classify ... rain' algorithms

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/limburg-flood-impact#8]
What happened:

- User selected "model extent" layer as "buildings" input for the "classify area wide rain" algorithm
- Algorithm took a long time and cancelling didn't work
- Running the same algorithm simultaneously with the correct input crashed QGIS

I think these kind of user mistakes can be prevented by adding some basic checks to see if the selected polygon layer is a buildings layer. 

Probably checking if the layer has an `identificatie` field would be enough

**Comment by JanCaha** [comment]
Which version of QGIS was used? All the processing tools in QGIS should run in non-blocking manner, being run on the background of the main application. I tested it and was able to run 4 instances of the algorithm at the same time, without QGIS being blocked. 

I am not sure what the solutions suggest? Using only part of the input data based on size or attribute?

**Comment by JanCaha** [comment]
Time estimates: 1 hour if the check only applies inside QGIS (2 if it needs to be for the python package as well)

**Comment by JanCaha** [comment]
The tool na requires the field to be present.

I also managed to make the tool properly cancelable from QGIS. So it should properly cancel in reasonable time if user clicks cancel.

Should this be part of all the classification tools? The remaining tools will probably suffer the same behaviour issues. It can still fit within the 2 hours scope.

**Comment by leendertvanwolfswinkel** [comment]
yes, it applies to:
- Classify Area Wide Rain
- Classify Urban Rain
- Classify Rural Rain

**Comment by JanCaha** [comment]
Added, will be part of next release.
